/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_Base 0x40021000
#define GPIOA_Base 0x40010800
#define EXTI_Base 0x40010400
#define AFIO_Base 0x40010000

//APB2 peripheral clock enable register
#define RCC_APB2ENR *((volatile unsigned int *)(RCC_Base+0x18))

//Port configuration register low (GPIOx_CRL) (x=A..G)
#define GPIOA_CRL *((volatile unsigned int *)(GPIOA_Base+0x00))
//Port configuration register High (GPIOx_CRH) (x=A..G)
#define GPIOA_CRH *((volatile unsigned int *)(GPIOA_Base+0x04))
#define GPIOA_ODR *((volatile unsigned int*)(GPIOA_Base+0x0C))

//External interrupt configuration register 1 (AFIO_EXTICR1)
#define AFIO_EXTICR1 *((volatile unsigned int *)(AFIO_Base+0x08))

//Interrupt mask register (EXTI_IMR)
#define EXTI_IMR *((volatile unsigned int *)(EXTI_Base+0x00))
//Rising trigger selection register (EXTI_RTSR)
#define EXTI_RTSR *((volatile unsigned int *)(EXTI_Base+0x08))
//Pending register (EXTI_PR)
#define EXTI_PR *((volatile unsigned int *)(EXTI_Base+0x14))

//NVIC_ISER0 Interrupt Set-Enable Registers
#define NVIC_ISER0 *((volatile unsigned int *)(0xE000E100))

void clk_init()
{
	//Alternate function IO clock enable
	RCC_APB2ENR |= 1<<0;
	//IO port A clock enable
	RCC_APB2ENR |=1<<2;
}

void GPIO_init()
{
	// 00: pA0 Input mode (reset state)
	GPIOA_CRL &=~(11<<0);
	//01(pins 2&3): Floating input pA0 (reset state)
	GPIOA_CRL |=1<<2;
	//pin 13 port A output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
}

int main(void)
{
	clk_init();
	GPIO_init();
	//initialize PA13 by 0
	GPIOA_ODR |=(1<<13);
	//select the source input for EXTI0 external interrupt.
	AFIO_EXTICR1 =0;
	//Enable NVIC interrupt request 6
	NVIC_ISER0|=1<<6;
	//Interrupt Mask on line 0
	EXTI_IMR |=1<<0;
	//Rising trigger event configuration bit of line 0
	EXTI_RTSR|=1<<0;
	while(1);

}
//ISR EXTI Line0 interrupt
void EXTI0_IRQHandler()
{
	//toggle led
	GPIOA_ODR ^=1<<13;
	//cleared pending register by writing a ‘1’ into the bit for line 0.
	EXTI_PR |=1<<0;

}
