/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include<stdio.h>
#include<stdint.h>
#include"platform_types.h"

#define RCC_BASE 0x40021000
#define PORTA_BASE 0x40010800

typedef union{
	vuint32_t allport;
	struct {
		vuint32_t reserve :2 ;
		vuint32_t p_2     :1 ;
	}Sbits;
}APB2ENR_t;

typedef union{
	vuint32_t allport;
	struct {
		vuint32_t reserve :20 ;
		vuint32_t p_20    :1 ;
		vuint32_t p_21    :1 ;
		vuint32_t p_22_23    :2 ;
	}Sbits;
}CRH_t;

typedef union{
	vuint32_t allport;
	struct {
		vuint32_t reserve :13 ;
		vuint32_t p_13     :1 ;
	}Sbits;
}GPIOA_ODR_t;

volatile APB2ENR_t* APB2ENR =(volatile APB2ENR_t*)(RCC_BASE + 0x18);
volatile CRH_t* CRH =(volatile CRH_t*)(PORTA_BASE + 0x04);
volatile GPIOA_ODR_t* R_ODR =(volatile GPIOA_ODR_t*)(PORTA_BASE + 0x0c);
unsigned char g_variable[3]={1,2,3};
unsigned char const const_variable[3]={1,2,3};

int main(void)
{
    int i;
    APB2ENR->Sbits.p_2=1; // set bit2

    CRH->Sbits.p_20=0;
    CRH->Sbits.p_21=1;
    CRH->Sbits.p_22_23=0;
    R_ODR->Sbits.p_13=1;
    while(1){

    for(i=0;i<5000;i++);
    R_ODR->Sbits.p_13^=1;

    }
   return 0;
}
