/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*Configure Board to run with the Following rates:
APB1 Bus frequency 16MHZ
APB2 Bus frequency 8MHZ
AHB frequency 32 MHZ
SysClk32 MHZ
Use only internal HSI_RC
 */
#define GPIOA_BASE 0x40010800
#define RCC_BASE 0x40021000
#define GPIOA_CRH *((volatile unsigned int*)(GPIOA_BASE+0x04))
#define GPIOA_ODR *((volatile unsigned int*)(GPIOA_BASE+0x0C))
#define RCC_APB2ENR *((volatile unsigned int*)(RCC_BASE+0x18))
#define RCC_CFGR *((volatile unsigned int*)(RCC_BASE+0x04))
#define RCC_CR *((volatile unsigned int*)(RCC_BASE+0x00))

void clk_init(){
	// select pll from sw(10)
	RCC_CFGR&=~(0b1);
	RCC_CFGR |=(1<<1);

	//PLL multiplier by 8(0110)
	RCC_CFGR &=~(1<<18);
	RCC_CFGR |=(0b11<<19);
	RCC_CFGR &=~(0b0<<21);

	RCC_CFGR&=~(0b1<<7);//AHB prescaler 1
	// PRE1 prescaler
	RCC_CFGR&=~(0b11<<8);
	RCC_CFGR|=(0b1<<10);
	// PRE2 prescaler
	RCC_CFGR|=(0b101<<11);
	RCC_CFGR&=~(0<<12);

	RCC_CR |=1<<24; //enable pll
}
int main(void)
{
	int i;
	clk_init();
	RCC_APB2ENR |=1<<2;
	GPIOA_CRH &=0xFF0FFFFF;
	GPIOA_CRH |=0x00200000;
	while(1)
	{
		GPIOA_ODR |=1<<13;
		for(i=0;i<5000;i++);

		GPIOA_ODR &=~(1<<13);
		for(i=0;i<5000;i++);
	}
}
